import Book1 from "../../static/images/book1.jpg";
import Book2 from "../../static/images/book2.jpg";
import Book3 from "../../static/images/book3.jpg";
import Book4 from "../../static/images/book4.jpg";

export const books = [
  {
    id: 1,
    bookName: "Good Enough: 40ish Devotionals for a Life of Imperfection",
    authorName: "Kate Bowler and Jessica Richie",
    price: 39.99,
    actualPrice: 32.99,
    isFree: false,
    coverImage: Book1,
  },
  {
    id: 2,
    bookName: "All about Love: New Visions",
    authorName: "Bell Hooks",
    price: null,
    actualPrice: null,
    isFree: true,
    coverImage: Book2,
  },
  {
    id: 3,
    bookName: "Good Enough: 40ish Devotionals for a Life of Imperfection",
    authorName: "Kate Bowler and Jessica Richie",
    price: 39.99,
    actualPrice: 32.99,
    isFree: false,
    coverImage: Book3,
  },
  {
    id: 4,
    bookName: "Good Enough: 40ish Devotionals for a Life of Imperfection",
    authorName: "Kate Bowler and Jessica Richie",
    price: 39.99,
    actualPrice: 32.99,
    isFree: false,
    coverImage: Book4,
  },
  {
    id: 5,
    bookName: "Good Enough: 40ish Devotionals for a Life of Imperfection",
    authorName: "Kate Bowler and Jessica Richie",
    price: 39.99,
    actualPrice: 32.99,
    isFree: false,
    coverImage: Book1,
  },
  {
    id: 6,
    bookName: "Good Enough: 40ish Devotionals for a Life of Imperfection",
    authorName: "Kate Bowler and Jessica Richie",
    price: 39.99,
    actualPrice: 32.99,
    isFree: false,
    coverImage: Book2,
  },
  {
    id: 7,
    bookName: "All about Love: New Visions",
    authorName: "Bell Hooks",
    price: null,
    actualPrice: null,
    isFree: true,
    coverImage: Book3,
  },
  {
    id: 8,
    bookName: "Good Enough: 40ish Devotionals for a Life of Imperfection",
    authorName: "Kate Bowler and Jessica Richie",
    price: 39.99,
    actualPrice: 32.99,
    isFree: false,
    coverImage: Book4,
  },
  {
    id: 9,
    bookName: "Good Enough: 40ish Devotionals for a Life of Imperfection",
    authorName: "Kate Bowler and Jessica Richie",
    price: 39.99,
    actualPrice: 32.99,
    isFree: false,
    coverImage: Book1,
  },
  {
    id: 10,
    bookName: "Good Enough: 40ish Devotionals for a Life of Imperfection",
    authorName: "Kate Bowler and Jessica Richie",
    price: 39.99,
    actualPrice: 32.99,
    isFree: false,
    coverImage: Book2,
  },
  {
    id: 11,
    bookName: "All about Love: New Visions",
    authorName: "Bell Hooks",
    price: null,
    actualPrice: null,
    isFree: true,
    coverImage: Book3,
  },
];
